export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      branchName: "AX Erdenet",
      seniorAccountant: "B.Solongo",
      seniorAccountantPhone: "99696966",
      billingAccountant: "Enkhbolor",
      billingAccountantPhone: "98989898",
      group: "bus",
    },
    {
      id: 2,
      branchName: "Ax Darkhan",
      seniorAccountant: "B.Nymbat",
      seniorAccountantPhone: "78945124",
      billingAccountant: "Munkhuu",
      billingAccountantPhone: "45612378",
      group: "hyper",
    },
    {
      id: 3,
      branchName: "Улаанбаатар",
      seniorAccountant: "Б. Нямдаг",
      seniorAccountantPhone: "78945124",
      billingAccountant: "Мөнхөө",
      billingAccountantPhone: "45612378",
      group: "club",
    },
    {
      id: 4,
      branchName: "Эрдэнэт",
      seniorAccountant: "Б. Баяраа",
      seniorAccountantPhone: "78945124",
      billingAccountant: "Сараа",
      billingAccountantPhone: "45612378",
      group: "club",
    },
    {
      id: 4,
      branchName: "Эрдэнэт",
      seniorAccountant: "Б. Баяраа",
      seniorAccountantPhone: "78945124",
      billingAccountant: "Сараа",
      billingAccountantPhone: "45612378",
      group: "hyper",
    },
    {
      id: 4,
      branchName: "Эрдэнэт",
      seniorAccountant: "Б. Баяраа",
      seniorAccountantPhone: "78945124",
      billingAccountant: "Сараа",
      billingAccountantPhone: "45612378",
      group: "bus",
    },
  ]);
}
